### ISSUE TITLE
mean function in R not working on numeric data

### ISSUE THREAD

**Issue by KellyAnnNeal** [KellyAnnNeal/FISH549#2]
https://gist.github.com/KellyAnnNeal/999281714df4d509a13e1f1f5b4aa266

**Comment by mdscheuerell** [comment]
This a good attempt at your reprex, but recall that you should submit a _minimal, reproducible example_, which means including **all** of the info in one location. I'd encourage you to go back and look over the [class notes](https://fish549.github.io/website/lectures/week_04/lec_11_getting_help.html).

**Comment by KellyAnnNeal** [comment]
I see I should have 1) included a sample subset of data, not all the whole
data set I was using, 2) had the line(s) of code needed to make my error
message I needed help with, and 3) included my session info meta data.
Thanks for including the answer key so I could see how I should have done
it.
